export type Product = {
  id: string;
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  badge?: 'NEW IN' | 'PREMIUM' | 'SALE';
  description: string;
  details: string[];
  images: string[];
  sizes: string[];
  colors: string[];
  fabric: string;
  inStock: boolean;
  featured?: boolean;
  isNew?: boolean;
};

export type Category = {
  name: string;
  slug: string;
  description: string;
  image: string;
  metaTitle: string;
  metaDescription: string;
};

export const categories: Category[] = [
  {
    name: 'Shalwar Kameez',
    slug: 'shalwar-kameez',
    description: 'Traditional Pakistani Shalwar Kameez crafted with premium fabrics',
    image: '/images/cat-shalwar-kameez.jpg',
    metaTitle: 'Shalwar Kameez Collection | VASTR – Premium Pakistani Menswear',
    metaDescription: 'Explore VASTR\'s curated collection of premium Shalwar Kameez. Handcrafted with finest fabrics for the modern Pakistani man.',
  },
  {
    name: 'Waistcoat',
    slug: 'waistcoat',
    description: 'Elegant waistcoats for every occasion',
    image: '/images/cat-waistcoat.jpg',
    metaTitle: 'Waistcoat Collection | VASTR – Luxury Menswear Pakistan',
    metaDescription: 'Shop VASTR\'s premium waistcoat collection. From formal to festive, find the perfect waistcoat for every occasion.',
  },
  {
    name: 'Prince Coat',
    slug: 'prince-coat',
    description: 'Regal Prince Coats for weddings and formal occasions',
    image: '/images/cat-prince-coat.jpg',
    metaTitle: 'Prince Coat Collection | VASTR – Wedding & Formal Menswear',
    metaDescription: 'Discover VASTR\'s Prince Coat collection. Premium quality, exquisite embroidery and timeless style for weddings and formal events.',
  },
  {
    name: 'Pent Coat',
    slug: 'pent-coat',
    description: 'Sharp Pent Coat suits for the modern gentleman',
    image: '/images/cat-pent-coat.jpg',
    metaTitle: 'Pent Coat Collection | VASTR – Men\'s Suits Pakistan',
    metaDescription: 'Shop VASTR\'s premium Pent Coat collection. Perfectly tailored suits for business, weddings and formal occasions.',
  },
  {
    name: 'Sherwani',
    slug: 'sherwani',
    description: 'Exquisite Sherwanis for your most special moments',
    image: '/images/cat-sherwani.jpg',
    metaTitle: 'Sherwani Collection | VASTR – Bridal & Wedding Sherwani',
    metaDescription: 'Find your perfect wedding Sherwani at VASTR. Premium bridal sherwanis with intricate embroidery and luxury fabrics.',
  },
  {
    name: 'Unstitched',
    slug: 'unstitched',
    description: 'Premium unstitched fabric for custom tailoring',
    image: '/images/cat-unstitched.jpg',
    metaTitle: 'Unstitched Fabric Collection | VASTR – Premium Fabric Pakistan',
    metaDescription: 'Shop VASTR\'s premium unstitched fabric collection. Lawn, cotton, silk and more for custom tailoring.',
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Complete your look with our curated accessories',
    image: '/images/cat-accessories.jpg',
    metaTitle: 'Men\'s Accessories | VASTR – Ties, Pocket Squares & More',
    metaDescription: 'Complete your VASTR look with our curated accessories collection. Ties, pocket squares, cufflinks and more.',
  },
];

export const products: Product[] = [
  // SHALWAR KAMEEZ
  {
    id: 'sk-001',
    slug: 'cotton-shalwar-kameez-white',
    name: 'Classic Cotton Shalwar Kameez',
    category: 'Shalwar Kameez',
    categorySlug: 'shalwar-kameez',
    price: 3200,
    badge: 'NEW IN',
    description: 'A timeless classic cotton Shalwar Kameez, perfect for daily wear and casual outings. Crafted from 100% premium cotton for all-day comfort.',
    details: ['100% Premium Cotton', 'Machine washable', 'Embroidered collar', 'Available in multiple colors'],
    images: ['/images/product/shalwar-kameez1.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Ivory', 'Light Blue'],
    fabric: 'Cotton',
    inStock: true,
    isNew: true,
    featured: true,
  },
  {
    id: 'sk-002',
    slug: 'premium-lawn-kameez-blue',
    name: 'Premium Lawn Kameez',
    category: 'Shalwar Kameez',
    categorySlug: 'shalwar-kameez',
    price: 4500,
    originalPrice: 6000,
    discount: 25,
    badge: 'SALE',
    description: 'Premium lawn fabric Kameez with delicate embroidery. Light and breathable, ideal for summer occasions.',
    details: ['Premium Lawn Fabric', 'Hand embroidered', 'Dry clean recommended', 'Comes with matching shalwar'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Green', 'Beige'],
    fabric: 'Lawn',
    inStock: true,
    featured: true,
  },
  {
    id: 'sk-003',
    slug: 'linen-shalwar-kameez-grey',
    name: 'Linen Shalwar Kameez',
    category: 'Shalwar Kameez',
    categorySlug: 'shalwar-kameez',
    price: 5800,
    badge: 'NEW IN',
    description: 'Sophisticated linen Shalwar Kameez for the modern man. Breathable and stylish for both formal and semi-formal occasions.',
    details: ['Pure Linen', 'Modern cut', 'Mandarin collar', 'Hand stitched'],
    images: ['/images/product/shalwar-kameez2.jpg'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Navy', 'Olive'],
    fabric: 'Linen',
    inStock: true,
    isNew: true,
  },
  {
    id: 'sk-004',
    slug: 'embroidered-eid-kameez',
    name: 'Embroidered Eid Kameez',
    category: 'Shalwar Kameez',
    categorySlug: 'shalwar-kameez',
    price: 7500,
    badge: 'PREMIUM',
    description: 'Ornate embroidered Kameez crafted for Eid and special occasions. Features intricate threadwork on collar and cuffs.',
    details: ['Premium Silk Blend', 'Hand embroidered', 'Dry clean only', 'Complete suit'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cream', 'Gold', 'Royal Blue'],
    fabric: 'Silk Blend',
    inStock: true,
  },
  {
    id: 'sk-005',
    slug: 'casual-kurta-set',
    name: 'Casual Kurta Set',
    category: 'Shalwar Kameez',
    categorySlug: 'shalwar-kameez',
    price: 2800,
    description: 'Relaxed fit casual kurta set for everyday elegance. Soft fabric with minimal detailing.',
    details: ['Cotton Blend', 'Regular fit', 'Minimal design', 'Easy care'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Brown', 'White'],
    fabric: 'Cotton Blend',
    inStock: true,
  },
  {
    id: 'sk-006',
    slug: 'luxury-jamawar-kameez',
    name: 'Luxury Jamawar Kameez',
    category: 'Shalwar Kameez',
    categorySlug: 'shalwar-kameez',
    price: 12000,
    badge: 'PREMIUM',
    description: 'Heritage Jamawar weave Kameez with rich patterns. A statement piece for weddings and festive occasions.',
    details: ['Jamawar Fabric', 'Traditional weave', 'Dry clean only', 'Limited edition'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Burgundy', 'Navy', 'Dark Green'],
    fabric: 'Jamawar',
    inStock: true,
    featured: true,
  },
  {
    id: 'sk-007',
    slug: 'slim-fit-kameez-black',
    name: 'Slim Fit Kameez',
    category: 'Shalwar Kameez',
    categorySlug: 'shalwar-kameez',
    price: 4200,
    badge: 'NEW IN',
    description: 'Contemporary slim fit Kameez for the fashion-forward man. Clean lines and modern silhouette.',
    details: ['Cotton Lawn', 'Slim fit cut', 'Hidden buttons', 'Structured collar'],
    images: ['/images/product/slim-fit-kameez.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Navy'],
    fabric: 'Cotton Lawn',
    inStock: true,
    isNew: true,
  },
  {
    id: 'sk-008',
    slug: 'festive-silk-kameez',
    name: 'Festive Silk Kameez',
    category: 'Shalwar Kameez',
    categorySlug: 'shalwar-kameez',
    price: 9500,
    originalPrice: 13000,
    discount: 27,
    badge: 'SALE',
    description: 'Pure silk Kameez with golden threadwork. Perfect for weddings, Mehndi and festive celebrations.',
    details: ['Pure Silk', 'Gold threadwork', 'Dry clean only', 'Premium packaging'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Gold', 'Ivory', 'Rose'],
    fabric: 'Pure Silk',
    inStock: true,
    featured: true,
  },

  // WAISTCOAT
  {
    id: 'wc-001',
    slug: 'classic-silk-waistcoat',
    name: 'Classic Silk Waistcoat',
    category: 'Waistcoat',
    categorySlug: 'waistcoat',
    price: 6500,
    badge: 'NEW IN',
    description: 'Timeless silk waistcoat with fine craftsmanship. Pairs beautifully with any Shalwar Kameez or suit.',
    details: ['Pure Silk', '5-button front', 'Embroidered lining', 'Tailored fit'],
    images: ['/images/product/waistcoat-newin.webp'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Burgundy'],
    fabric: 'Silk',
    inStock: true,
    isNew: true,
    featured: true,
  },
  {
    id: 'wc-002',
    slug: 'embroidered-bridal-waistcoat',
    name: 'Embroidered Bridal Waistcoat',
    category: 'Waistcoat',
    categorySlug: 'waistcoat',
    price: 9800,
    badge: 'PREMIUM',
    description: 'Heavily embroidered waistcoat for Barat and wedding occasions. Intricate zardozi work on premium fabric.',
    details: ['Velvet Base', 'Zardozi embroidery', 'Gold buttons', 'Dry clean only'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Gold', 'Maroon', 'Royal Blue'],
    fabric: 'Velvet',
    inStock: true,
    featured: true,
  },
  {
    id: 'wc-003',
    slug: 'casual-cotton-waistcoat',
    name: 'Casual Cotton Waistcoat',
    category: 'Waistcoat',
    categorySlug: 'waistcoat',
    price: 3500,
    description: 'Lightweight cotton waistcoat for daily and semi-formal wear. Minimalist design, maximum elegance.',
    details: ['100% Cotton', 'Breathable', '4-pocket design', 'Machine washable'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Beige', 'Grey', 'White'],
    fabric: 'Cotton',
    inStock: true,
  },
  {
    id: 'wc-004',
    slug: 'jamawar-waistcoat',
    name: 'Jamawar Waistcoat',
    category: 'Waistcoat',
    categorySlug: 'waistcoat',
    price: 8200,
    originalPrice: 11000,
    discount: 25,
    badge: 'SALE',
    description: 'Rich Jamawar weave waistcoat. A statement piece that commands attention at any formal gathering.',
    details: ['Jamawar Fabric', 'Brocade lining', 'Antique buttons', 'Dry clean only'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Teal', 'Burgundy', 'Gold'],
    fabric: 'Jamawar',
    inStock: true,
  },
  {
    id: 'wc-005',
    slug: 'linen-waistcoat-summer',
    name: 'Summer Linen Waistcoat',
    category: 'Waistcoat',
    categorySlug: 'waistcoat',
    price: 4800,
    badge: 'NEW IN',
    description: 'Breathable linen waistcoat perfect for summer weddings and daytime events.',
    details: ['Pure Linen', 'Light weight', 'Natural texture', 'Easy care'],
    images: ['/images/product/waistcoat-new.webp'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Tan', 'Sage'],
    fabric: 'Linen',
    inStock: true,
    isNew: true,
  },
  {
    id: 'wc-006',
    slug: 'velvet-winter-waistcoat',
    name: 'Velvet Winter Waistcoat',
    category: 'Waistcoat',
    categorySlug: 'waistcoat',
    price: 7500,
    description: 'Luxurious velvet waistcoat for winter occasions. Rich texture with elegant finish.',
    details: ['Premium Velvet', 'Silk lining', 'Ornate buttons', 'Dry clean only'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Deep Burgundy', 'Forest Green', 'Midnight Blue'],
    fabric: 'Velvet',
    inStock: true,
  },
  {
    id: 'wc-007',
    slug: 'printed-cotton-waistcoat',
    name: 'Printed Cotton Waistcoat',
    category: 'Waistcoat',
    categorySlug: 'waistcoat',
    price: 3200,
    badge: 'SALE',
    originalPrice: 4500,
    discount: 30,
    description: 'Contemporary printed cotton waistcoat. Modern patterns meet traditional craftsmanship.',
    details: ['Cotton', 'Block print', '4-button closure', 'Machine washable'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Multicolor', 'Blue Print', 'Red Print'],
    fabric: 'Cotton',
    inStock: true,
  },
  {
    id: 'wc-008',
    slug: 'premium-raw-silk-waistcoat',
    name: 'Raw Silk Waistcoat',
    category: 'Waistcoat',
    categorySlug: 'waistcoat',
    price: 11000,
    badge: 'PREMIUM',
    description: 'Exclusive raw silk waistcoat with handcrafted detail. For the man who appreciates true luxury.',
    details: ['Raw Silk', 'Hand stitched', 'Mother of pearl buttons', 'Bespoke available'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Champagne', 'Slate', 'Black'],
    fabric: 'Raw Silk',
    inStock: true,
    featured: true,
  },

  // PRINCE COAT
  {
    id: 'pc-001',
    slug: 'royal-prince-coat-navy',
    name: 'Royal Prince Coat',
    category: 'Prince Coat',
    categorySlug: 'prince-coat',
    price: 18500,
    badge: 'NEW IN',
    description: 'Majestic Prince Coat crafted for royalty. Perfect for Barat and Walima ceremonies.',
    details: ['Wool Blend', 'Sherwani collar', 'Gold buttons', 'Tailored fit'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'Black', 'Charcoal'],
    fabric: 'Wool Blend',
    inStock: true,
    isNew: true,
    featured: true,
  },
  {
    id: 'pc-002',
    slug: 'embroidered-prince-coat-cream',
    name: 'Embroidered Prince Coat',
    category: 'Prince Coat',
    categorySlug: 'prince-coat',
    price: 25000,
    badge: 'PREMIUM',
    description: 'Premium embroidered Prince Coat for the groom. Hand-crafted with intricate threadwork and zardozi.',
    details: ['Premium Fabric', 'Zardozi embroidery', 'Silk lining', 'Comes with matching shalwar'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Cream', 'Ivory', 'Off-White'],
    fabric: 'Premium Blend',
    inStock: true,
    featured: true,
  },
  {
    id: 'pc-003',
    slug: 'slim-fit-prince-coat-black',
    name: 'Slim Fit Prince Coat',
    category: 'Prince Coat',
    categorySlug: 'prince-coat',
    price: 15000,
    originalPrice: 20000,
    discount: 25,
    badge: 'SALE',
    description: 'Modern slim fit Prince Coat for the contemporary groom. Clean silhouette with subtle detailing.',
    details: ['Tweed Blend', 'Slim cut', 'Satin lining', 'Professional tailoring'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Midnight Blue', 'Charcoal'],
    fabric: 'Tweed Blend',
    inStock: true,
  },
  {
    id: 'pc-004',
    slug: 'velvet-prince-coat-maroon',
    name: 'Velvet Prince Coat',
    category: 'Prince Coat',
    categorySlug: 'prince-coat',
    price: 28000,
    badge: 'PREMIUM',
    description: 'Opulent velvet Prince Coat for winter weddings. Rich texture with gold embellishments.',
    details: ['Premium Velvet', 'Gold threadwork', 'Padded shoulders', 'Dry clean only'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Maroon', 'Burgundy', 'Deep Green'],
    fabric: 'Velvet',
    inStock: true,
  },
  {
    id: 'pc-005',
    slug: 'classic-prince-coat-grey',
    name: 'Classic Prince Coat',
    category: 'Prince Coat',
    categorySlug: 'prince-coat',
    price: 14500,
    badge: 'NEW IN',
    description: 'Timeless classic Prince Coat that transcends trends. Refined and elegant for any formal occasion.',
    details: ['Wool', 'Classic cut', 'Horn buttons', 'Structured fit'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Dark Grey', 'Navy'],
    fabric: 'Wool',
    inStock: true,
    isNew: true,
  },
  {
    id: 'pc-006',
    slug: 'jamawar-prince-coat',
    name: 'Jamawar Prince Coat',
    category: 'Prince Coat',
    categorySlug: 'prince-coat',
    price: 32000,
    badge: 'PREMIUM',
    description: 'Heritage Jamawar Prince Coat for the most discerning groom. A masterpiece of Pakistani craftsmanship.',
    details: ['Jamawar Fabric', 'Hand embroidered', 'Silk lining', 'Limited edition'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Gold Jamawar', 'Blue Jamawar', 'Green Jamawar'],
    fabric: 'Jamawar',
    inStock: true,
    featured: true,
  },
  {
    id: 'pc-007',
    slug: 'modern-prince-coat-beige',
    name: 'Modern Prince Coat',
    category: 'Prince Coat',
    categorySlug: 'prince-coat',
    price: 16500,
    description: 'Contemporary Prince Coat blending traditional style with modern aesthetics.',
    details: ['Linen Blend', 'Modern design', 'Concealed buttons', 'Tailored silhouette'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Beige', 'Camel', 'Stone'],
    fabric: 'Linen Blend',
    inStock: true,
  },
  {
    id: 'pc-008',
    slug: 'digital-print-prince-coat',
    name: 'Digital Print Prince Coat',
    category: 'Prince Coat',
    categorySlug: 'prince-coat',
    price: 19000,
    originalPrice: 25000,
    discount: 24,
    badge: 'SALE',
    description: 'Artistic digital print Prince Coat for the bold groom. Unique patterns make a statement at every event.',
    details: ['Digital Print Fabric', 'Unique pattern', 'Satin lining', 'Fashion forward'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Multicolor', 'Blue Pattern', 'Gold Pattern'],
    fabric: 'Print Fabric',
    inStock: true,
  },

  // PENT COAT
  {
    id: 'pec-001',
    slug: 'premium-pent-coat-charcoal',
    name: 'Premium Pent Coat',
    category: 'Pent Coat',
    categorySlug: 'pent-coat',
    price: 22000,
    badge: 'PREMIUM',
    description: 'Premium Pent Coat suit for business and formal occasions. Sharp tailoring meets luxurious comfort.',
    details: ['Wool Blend', '2-button closure', 'Notch lapel', 'Fully lined'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Navy', 'Black'],
    fabric: 'Wool Blend',
    inStock: true,
    featured: true,
  },
  {
    id: 'pec-002',
    slug: 'slim-fit-pent-coat-navy',
    name: 'Slim Fit Pent Coat',
    category: 'Pent Coat',
    categorySlug: 'pent-coat',
    price: 18500,
    badge: 'NEW IN',
    description: 'Modern slim fit suit for the contemporary professional. Clean lines and impeccable tailoring.',
    details: ['Italian Fabric', 'Slim fit', 'Peak lapel', 'Half canvas construction'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Royal Blue', 'Teal'],
    fabric: 'Italian Blend',
    inStock: true,
    isNew: true,
    featured: true,
  },
  {
    id: 'pec-003',
    slug: 'wedding-pent-coat-white',
    name: 'Wedding Pent Coat',
    category: 'Pent Coat',
    categorySlug: 'pent-coat',
    price: 28000,
    badge: 'PREMIUM',
    description: 'Elegant white Pent Coat suit for grooms and festive occasions. Pure sophistication.',
    details: ['Premium Wool', 'White satin lining', 'Embroidered lapel', 'Bespoke options'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['White', 'Cream', 'Off-White'],
    fabric: 'Premium Wool',
    inStock: true,
  },
  {
    id: 'pec-004',
    slug: 'business-pent-coat-grey',
    name: 'Business Pent Coat',
    category: 'Pent Coat',
    categorySlug: 'pent-coat',
    price: 15500,
    originalPrice: 20000,
    discount: 22,
    badge: 'SALE',
    description: 'Professional business suit for corporate settings. Classic design that never goes out of style.',
    details: ['Tropical Wool', 'Regular fit', 'Notch lapel', 'Side vents'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Dark Grey', 'Charcoal'],
    fabric: 'Tropical Wool',
    inStock: true,
  },
  {
    id: 'pec-005',
    slug: 'tweed-pent-coat-brown',
    name: 'Tweed Pent Coat',
    category: 'Pent Coat',
    categorySlug: 'pent-coat',
    price: 24000,
    badge: 'NEW IN',
    description: 'Heritage tweed Pent Coat with character and depth. For the man who values tradition.',
    details: ['Harris Tweed', 'Patch pockets', 'Horn buttons', 'Fully lined'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Brown Tweed', 'Green Tweed', 'Grey Tweed'],
    fabric: 'Tweed',
    inStock: true,
    isNew: true,
  },
  {
    id: 'pec-006',
    slug: 'double-breasted-pent-coat',
    name: 'Double Breasted Suit',
    category: 'Pent Coat',
    categorySlug: 'pent-coat',
    price: 26500,
    badge: 'PREMIUM',
    description: 'Bold double-breasted suit making a powerful statement. Authority meets elegance.',
    details: ['Premium Wool', 'Double breasted', 'Peak lapel', 'Full canvas'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Navy', 'Black', 'Charcoal'],
    fabric: 'Premium Wool',
    inStock: true,
    featured: true,
  },
  {
    id: 'pec-007',
    slug: 'linen-summer-pent-coat',
    name: 'Summer Linen Suit',
    category: 'Pent Coat',
    categorySlug: 'pent-coat',
    price: 16000,
    description: 'Breathable linen suit for summer events. Stay cool and stylish in the heat.',
    details: ['Pure Linen', 'Unlined jacket', 'Pleated trousers', 'Natural texture'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Beige', 'White', 'Light Blue'],
    fabric: 'Linen',
    inStock: true,
  },
  {
    id: 'pec-008',
    slug: 'velvet-dinner-jacket',
    name: 'Velvet Dinner Jacket',
    category: 'Pent Coat',
    categorySlug: 'pent-coat',
    price: 32000,
    originalPrice: 40000,
    discount: 20,
    badge: 'SALE',
    description: 'Sumptuous velvet dinner jacket for black tie and gala events. The pinnacle of formal dressing.',
    details: ['Silk Velvet', 'Shawl collar', 'Satin trim', 'Satin lining'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Midnight Blue', 'Black', 'Forest Green'],
    fabric: 'Silk Velvet',
    inStock: true,
  },

  // SHERWANI
  {
    id: 'sh-001',
    slug: 'bridal-sherwani-gold',
    name: 'Bridal Sherwani',
    category: 'Sherwani',
    categorySlug: 'sherwani',
    price: 35000,
    badge: 'PREMIUM',
    description: 'The ultimate bridal Sherwani for the most important day of your life. Exquisite handcrafted embroidery on finest fabric.',
    details: ['Pure Silk', 'Zardozi embroidery', 'Gold thread work', 'Comes with churidar & dupatta'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Gold', 'Ivory Gold', 'Champagne'],
    fabric: 'Pure Silk',
    inStock: true,
    featured: true,
  },
  {
    id: 'sh-002',
    slug: 'classic-black-sherwani',
    name: 'Classic Black Sherwani',
    category: 'Sherwani',
    categorySlug: 'sherwani',
    price: 28000,
    badge: 'NEW IN',
    description: 'Timeless black Sherwani for grooms and formal occasions. Understated luxury with refined details.',
    details: ['Premium Fabric', 'Silver embroidery', 'Churidar included', 'Custom sizing available'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Black Silver', 'Black Gold'],
    fabric: 'Premium Blend',
    inStock: true,
    isNew: true,
    featured: true,
  },
  {
    id: 'sh-003',
    slug: 'maroon-velvet-sherwani',
    name: 'Maroon Velvet Sherwani',
    category: 'Sherwani',
    categorySlug: 'sherwani',
    price: 42000,
    badge: 'PREMIUM',
    description: 'Opulent maroon velvet Sherwani for Barat ceremonies. Rich color and lavish embellishments.',
    details: ['Premium Velvet', 'Heavy embroidery', 'Gold kaam', 'Dry clean only'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Maroon', 'Deep Red', 'Wine'],
    fabric: 'Velvet',
    inStock: true,
  },
  {
    id: 'sh-004',
    slug: 'royal-blue-sherwani',
    name: 'Royal Blue Sherwani',
    category: 'Sherwani',
    categorySlug: 'sherwani',
    price: 32000,
    originalPrice: 42000,
    discount: 24,
    badge: 'SALE',
    description: 'Regal royal blue Sherwani that commands attention. Rich embroidery on deep blue fabric.',
    details: ['Silk Blend', 'Silver embroidery', 'Matching churidar', 'Sequin detailing'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Royal Blue', 'Sapphire', 'Midnight Blue'],
    fabric: 'Silk Blend',
    inStock: true,
    featured: true,
  },
  {
    id: 'sh-005',
    slug: 'ivory-walima-sherwani',
    name: 'Ivory Walima Sherwani',
    category: 'Sherwani',
    categorySlug: 'sherwani',
    price: 30000,
    badge: 'NEW IN',
    description: 'Pristine ivory Sherwani ideal for Walima ceremony. Light and elegant with delicate embroidery.',
    details: ['Silk Dupion', 'Light embroidery', 'Matching accessories', 'Complete set'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Ivory', 'Off-White', 'Pearl'],
    fabric: 'Silk Dupion',
    inStock: true,
    isNew: true,
  },
  {
    id: 'sh-006',
    slug: 'emerald-green-sherwani',
    name: 'Emerald Sherwani',
    category: 'Sherwani',
    categorySlug: 'sherwani',
    price: 38000,
    badge: 'PREMIUM',
    description: 'Striking emerald green Sherwani with golden embroidery. An unforgettable choice for the bold groom.',
    details: ['Jamawar Base', 'Gold embroidery', 'Full lining', 'Statement piece'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Emerald', 'Forest Green', 'Sage Green'],
    fabric: 'Jamawar',
    inStock: true,
  },
  {
    id: 'sh-007',
    slug: 'grey-contemporary-sherwani',
    name: 'Contemporary Sherwani',
    category: 'Sherwani',
    categorySlug: 'sherwani',
    price: 24000,
    description: 'Modern interpretation of the classic Sherwani. Minimal design for the understated groom.',
    details: ['Premium Cotton', 'Minimal embroidery', 'Slim fit', 'Versatile styling'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Grey', 'Steel Blue', 'Taupe'],
    fabric: 'Premium Cotton',
    inStock: true,
  },
  {
    id: 'sh-008',
    slug: 'heritage-jamawar-sherwani',
    name: 'Heritage Jamawar Sherwani',
    category: 'Sherwani',
    categorySlug: 'sherwani',
    price: 55000,
    badge: 'PREMIUM',
    description: 'The crown jewel of our collection. Heritage Jamawar Sherwani with museum-quality craftsmanship.',
    details: ['Antique Jamawar', 'Hand embroidered', 'Silk lining', 'Heirloom quality'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Antique Gold', 'Classic Maroon', 'Traditional Blue'],
    fabric: 'Antique Jamawar',
    inStock: true,
    featured: true,
  },

  // UNSTITCHED
  {
    id: 'un-001',
    slug: 'premium-lawn-fabric',
    name: 'Premium Lawn Fabric',
    category: 'Unstitched',
    categorySlug: 'unstitched',
    price: 1200,
    badge: 'NEW IN',
    description: 'Fine lawn fabric for summer wear. Soft, breathable and perfect for custom tailoring.',
    details: ['100% Lawn', '3m length', 'Colorfast', 'Machine washable'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['3m', '4m', '5m'],
    colors: ['White', 'Sky Blue', 'Mint', 'Peach'],
    fabric: 'Lawn',
    inStock: true,
    isNew: true,
  },
  {
    id: 'un-002',
    slug: 'pure-cotton-fabric',
    name: 'Pure Cotton Fabric',
    category: 'Unstitched',
    categorySlug: 'unstitched',
    price: 900,
    description: 'Classic cotton fabric for year-round comfort. Easy to care for and durable.',
    details: ['100% Cotton', '3m length', 'Pre-shrunk', 'Easy care'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['3m', '4m', '5m'],
    colors: ['White', 'Beige', 'Light Grey', 'Navy'],
    fabric: 'Cotton',
    inStock: true,
  },
  {
    id: 'un-003',
    slug: 'boski-fabric-premium',
    name: 'Boski Fabric',
    category: 'Unstitched',
    categorySlug: 'unstitched',
    price: 4000,
    originalPrice: 5500,
    discount: 27,
    badge: 'SALE',
    description: 'Premium Boski fabric for formal and semi-formal garments. Lightweight with a beautiful drape.',
    details: ['Premium Boski', '3m length', 'Dry clean only', 'Formal use'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['3m', '4m'],
    colors: ['Black', 'Navy', 'Charcoal', 'Grey'],
    fabric: 'Boski',
    inStock: true,
    featured: true,
  },
  {
    id: 'un-004',
    slug: 'embroidered-jacquard',
    name: 'Embroidered Jacquard',
    category: 'Unstitched',
    categorySlug: 'unstitched',
    price: 6500,
    badge: 'PREMIUM',
    description: 'Luxurious embroidered Jacquard for special occasion garments. Rich patterns woven into the fabric.',
    details: ['Jacquard Weave', 'Self embroidered', '2.5m length', 'Dry clean'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['2.5m', '3m'],
    colors: ['Gold', 'Silver', 'Maroon', 'Blue'],
    fabric: 'Jacquard',
    inStock: true,
  },
  {
    id: 'un-005',
    slug: 'linen-fabric-natural',
    name: 'Natural Linen Fabric',
    category: 'Unstitched',
    categorySlug: 'unstitched',
    price: 2200,
    badge: 'NEW IN',
    description: 'Natural linen fabric with earthy texture. Perfect for summer Shalwar Kameez and casual wear.',
    details: ['Pure Linen', '3m length', 'Natural texture', 'Gets softer with wash'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['3m', '4m', '5m'],
    colors: ['Natural', 'Sand', 'Grey', 'White'],
    fabric: 'Linen',
    inStock: true,
    isNew: true,
  },
  {
    id: 'un-006',
    slug: 'silk-fabric-premium',
    name: 'Pure Silk Fabric',
    category: 'Unstitched',
    categorySlug: 'unstitched',
    price: 8500,
    badge: 'PREMIUM',
    description: 'Pure silk fabric for the most special garments. Luxurious feel and beautiful sheen.',
    details: ['Pure Silk', '2.5m length', 'Dry clean only', 'Heirloom quality'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['2.5m', '3m'],
    colors: ['Ivory', 'Champagne', 'Navy', 'Black'],
    fabric: 'Pure Silk',
    inStock: true,
  },
  {
    id: 'un-007',
    slug: 'khaddar-winter-fabric',
    name: 'Winter Khaddar',
    category: 'Unstitched',
    categorySlug: 'unstitched',
    price: 1500,
    description: 'Warm and cozy Khaddar fabric for winter garments. Traditional texture with modern colors.',
    details: ['Khaddar', '3m length', 'Machine washable', 'Winter weight'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['3m', '4m', '5m'],
    colors: ['Brown', 'Olive', 'Rust', 'Navy'],
    fabric: 'Khaddar',
    inStock: true,
  },
  {
    id: 'un-008',
    slug: 'jamawar-fabric-bridal',
    name: 'Bridal Jamawar Fabric',
    category: 'Unstitched',
    categorySlug: 'unstitched',
    price: 12000,
    originalPrice: 16000,
    discount: 25,
    badge: 'SALE',
    description: 'Heritage Jamawar fabric for bridal and festive garments. Intricate woven patterns of extraordinary beauty.',
    details: ['Authentic Jamawar', '3m length', 'Dry clean only', 'Heritage craft'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['3m', '4m'],
    colors: ['Gold Jamawar', 'Red Jamawar', 'Blue Jamawar'],
    fabric: 'Jamawar',
    inStock: true,
    featured: true,
  },

  // ACCESSORIES
  {
    id: 'ac-001',
    slug: 'silk-pocket-square-cream',
    name: 'Silk Pocket Square',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 800,
    badge: 'NEW IN',
    description: 'Elegant silk pocket square to complete your formal look. Hand-rolled edges and vibrant prints.',
    details: ['Pure Silk', 'Hand rolled edges', 'Multiple folds possible', 'Gift boxed'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['One Size'],
    colors: ['Cream', 'Navy', 'Burgundy', 'Gold'],
    fabric: 'Silk',
    inStock: true,
    isNew: true,
  },
  {
    id: 'ac-002',
    slug: 'woven-silk-necktie',
    name: 'Woven Silk Necktie',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 2500,
    description: 'Luxurious woven silk necktie for formal occasions. Classic patterns with contemporary colors.',
    details: ['Woven Silk', 'Interlining', 'Keeper loop', 'Gift boxed'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['Standard'],
    colors: ['Navy Stripe', 'Burgundy', 'Gold Paisley'],
    fabric: 'Silk',
    inStock: true,
  },
  {
    id: 'ac-003',
    slug: 'gold-cufflinks-set',
    name: 'Gold Cufflinks',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 3500,
    badge: 'PREMIUM',
    description: 'Premium gold-plated cufflinks for the discerning gentleman. Subtle detail that speaks volumes.',
    details: ['Gold plated', 'T-bar closure', 'Presentation box', 'Hypoallergenic'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['One Size'],
    colors: ['Gold', 'Silver', 'Rose Gold'],
    fabric: 'Metal',
    inStock: true,
  },
  {
    id: 'ac-004',
    slug: 'leather-belt-brown',
    name: 'Premium Leather Belt',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 4200,
    originalPrice: 6000,
    discount: 30,
    badge: 'SALE',
    description: 'Full-grain leather belt with polished buckle. A wardrobe essential for every man.',
    details: ['Full-grain Leather', 'Solid brass buckle', 'Hand stitched edges', 'Multiple widths'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['32', '34', '36', '38', '40'],
    colors: ['Tan', 'Dark Brown', 'Black'],
    fabric: 'Leather',
    inStock: true,
    featured: true,
  },
  {
    id: 'ac-005',
    slug: 'embroidered-khussa',
    name: 'Embroidered Khussa',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 5500,
    badge: 'NEW IN',
    description: 'Traditional embroidered Khussa for weddings and formal occasions. Handcrafted by skilled artisans.',
    details: ['Genuine Leather', 'Hand embroidered', 'Traditional craft', 'Cushioned insole'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Gold Embroidered', 'Silver Embroidered', 'Multi Color'],
    fabric: 'Leather',
    inStock: true,
    isNew: true,
    featured: true,
  },
  {
    id: 'ac-006',
    slug: 'shawl-pashmina',
    name: 'Pashmina Shawl',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 8000,
    badge: 'PREMIUM',
    description: 'Authentic Kashmiri Pashmina shawl. Incredibly soft and warm, a true luxury accessory.',
    details: ['Pure Pashmina', 'Hand woven', 'Traditional Kashmiri', 'Gift wrapped'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['Standard'],
    colors: ['Ivory', 'Camel', 'Charcoal', 'Navy'],
    fabric: 'Pashmina',
    inStock: true,
  },
  {
    id: 'ac-007',
    slug: 'karakul-cap',
    name: 'Karakul Cap',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 6500,
    description: 'Traditional Karakul cap, the iconic symbol of Pakistani formal wear. Pairs perfectly with Sherwani.',
    details: ['Genuine Karakul', 'Handcrafted', 'Traditional style', 'Prestige accessory'],
    images: ['/images/placeholder-light.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown', 'Grey'],
    fabric: 'Karakul Fur',
    inStock: true,
  },
  {
    id: 'ac-008',
    slug: 'topi-embroidered',
    name: 'Embroidered Topi',
    category: 'Accessories',
    categorySlug: 'accessories',
    price: 1500,
    originalPrice: 2200,
    discount: 32,
    badge: 'SALE',
    description: 'Traditional embroidered Topi for Eid, prayers and formal occasions. Beautifully crafted with intricate patterns.',
    details: ['Cotton Base', 'Hand embroidered', 'Traditional design', 'Multiple sizes'],
    images: ['/images/placeholder-dark.jpg'],
    sizes: ['S', 'M', 'L'],
    colors: ['White', 'Cream', 'Off-White'],
    fabric: 'Cotton',
    inStock: true,
  },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter(p => p.categorySlug === categorySlug);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.featured).slice(0, 8);
}

export function getNewArrivals(): Product[] {
  return products.filter(p => p.isNew).slice(0, 8);
}

export function getSaleProducts(): Product[] {
  return products.filter(p => p.badge === 'SALE').slice(0, 8);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find(c => c.slug === slug);
}

export function formatPrice(price: number): string {
  return `Rs. ${price.toLocaleString('en-PK')}`;
}

